/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: db929df92515895babfb9062eebb5fe2)
interface __BaseEnv_Env {
	DOCS_DB: D1Database;
	AI: Ai;
	AI_GATEWAY_ID: "squig-webmcp";
	SQUIG_FAKE_MODEL: "false";
	ACCESS_APPLICATION_AUD: "";
	ACCESS_TEAM_DOMAIN: "";
	APP_ORIGIN: "http://localhost:3000";
	ENVIRONMENT: "production";
	SquigDoc: DurableObjectNamespace<import("./worker/index").SquigDoc>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "SquigDoc";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID" | "SQUIG_FAKE_MODEL" | "ACCESS_APPLICATION_AUD" | "ACCESS_TEAM_DOMAIN" | "APP_ORIGIN" | "ENVIRONMENT">> {}
}
