/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fe07a4b058abf03014423e7c12e5285f)
interface __BaseEnv_Env {
	DOCS_DB: D1Database;
	AI_GATEWAY_ID: "squig-webmcp";
	APP_ORIGIN: "http://localhost:3000";
	ENVIRONMENT: "production";
	SquigDoc: DurableObjectNamespace<import("./worker/index").SquigDoc>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "SquigDoc";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_GATEWAY_ID" | "APP_ORIGIN" | "ENVIRONMENT">> {}
}
